# Generated by Django 4.2.13 on 2025-03-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_routeexclusion_required_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.TextField(default=None)),
                ('folder_directory', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_trained_state', models.DateField(default=None)),
                ('accuracy', models.TextField(default=None)),
                ('precision', models.TextField(default=None)),
                ('recall', models.TextField(default=None)),
                ('f1_score', models.TextField(default=None)),
            ],
        ),
    ]
