# Generated by Django 4.2.13 on 2025-03-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_disease_modelinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease_name',
            field=models.TextField(default='No Disease'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='folder_directory',
            field=models.TextField(default='No Folder'),
        ),
    ]
