# Generated by Django 4.2.13 on 2025-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_disease_disease_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(default='No Description'),
        ),
    ]
