# Generated by Django 4.2.13 on 2025-03-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_disease_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FileField(upload_to='media/datasets')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disease')),
            ],
        ),
    ]
