# Generated by Django 4.2.13 on 2025-03-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='location',
            field=models.FileField(upload_to='datasets'),
        ),
    ]
