# Generated by Django 4.2.13 on 2025-03-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_images_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='folder_directory',
        ),
    ]
