# Generated by Django 4.2.13 on 2025-03-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_pathologist_patient_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='fname',
            field=models.TextField(null=True),
        ),
    ]
