# Generated by Django 4.2.2 on 2025-03-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_prediction_smear_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='used_for',
            field=models.CharField(default='No Remark', max_length=255),
        ),
    ]
