# Generated by Django 4.2.2 on 2025-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_pathologist_user_prediction_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathologist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pathologist',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pathologist',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='pathologist',
            name='e_signature',
            field=models.FileField(null=True, upload_to='pathologist_signature'),
        ),
        migrations.AddField(
            model_name='pathologist',
            name='suffixes',
            field=models.TextField(default=None, null=True),
        ),
    ]
