# Generated by Django 4.2.2 on 2025-06-01 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_prediction_original_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bone_joint_pain',
            field=models.BooleanField(default=False, help_text='Unexplained pain in bones or joints?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fatigue',
            field=models.BooleanField(default=False, help_text='Feeling unusually tired or fatigued?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='frequent_infections',
            field=models.BooleanField(default=False, help_text='Frequent infections?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='general_unwell',
            field=models.BooleanField(default=False, help_text='General feeling of being unwell?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='night_sweats',
            field=models.BooleanField(default=False, help_text='Night sweats or chills?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pale_skin',
            field=models.BooleanField(default=False, help_text='Pale skin or looking more pale than usual?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='persistent_fever',
            field=models.BooleanField(default=False, help_text='Persistent or unexplained fevers?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='shortness_of_breath',
            field=models.BooleanField(default=False, help_text='Shortness of breath or rapid heartbeat with mild activity?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='swelling',
            field=models.BooleanField(default=False, help_text='Swelling in neck, underarms, or abdomen?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_loss',
            field=models.BooleanField(default=False, help_text='Unintentional weight loss?'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='date_of_diagnosis',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 0, 35, 30, 811397), null=True),
        ),
    ]
