# Generated by Django 4.2.2 on 2025-09-02 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_patient_email_alter_prediction_date_of_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologist',
            name='license_no',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='date_of_diagnosis',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 23, 18, 34, 145339), null=True),
        ),
    ]
